ask user for permission before removing backups

diff --git a/usr/bin/lernstick_backup b/usr/bin/lernstick_backup
--- a/usr/bin/lernstick_backup
+++ b/usr/bin/lernstick_backup
@@ -9,17 +9,17 @@ LOG_FILE="/var/log/lernstick_backup"
 # read config file
 # (sourcing doesn't work when properties have whitespaces)
 CONFIG_FILE="/etc/lernstickWelcome"
-if [ -f ${CONFIG_FILE} ]
+if [ -f $CONFIG_FILE ]
 then
 	declare -A CONFIG
 	IFS="="
 	while read -r key value
 	do
-		CONFIG[${key}]="${value}"
-	done < ${CONFIG_FILE}
+		CONFIG[$key]="$value"
+	done < $CONFIG_FILE
 	unset IFS
 else
-	echo "${CONFIG_FILE} does not (yet) exist" | tee -a ${LOG_FILE}
+	echo "$CONFIG_FILE does not (yet) exist" | tee -a $LOG_FILE
 	exit 0
 fi
 
@@ -27,49 +27,49 @@ SCREENSHOT_DIRECTORY="${CONFIG[BackupSource]}/.Screenshots"
 
 if [ "${CONFIG[Backup]}" != "true" ]
 then
-	echo "continuous backup is not enabled" | tee -a ${LOG_FILE}
+	echo "continuous backup is not enabled" | tee -a $LOG_FILE
 	exit 0
 fi
 
 show_error()
 {
-	TEXT="${1}"
-	BLOCKING="${2}"
+	TEXT="$1"
+	BLOCKING="$2"
 
 	if [ "$KDE_FULL_SESSION" ]
 	then
-		if [ "${BLOCKING}" = "true" ]
+		if [ "$BLOCKING" = "true" ]
 		then
-			sudo -u user kdialog --error "${TEXT}"
+			sudo -u user kdialog --error "$TEXT"
 		else
-			sudo -u user kdialog --error "${TEXT}" &
+			sudo -u user kdialog --error "$TEXT" &
 		fi
 	else
 		# zenity's HTML interpreter is so dumb, it doesn't even understand <br>...
-		# we need to replace it with "\\n"
-		ZENITY_TEXT="$(echo ${TEXT} | sed 's/<br>/\\n/g')"
-		echo "ZENITY_TEXT=\"${ZENITY_TEXT}\""
-		if [ "${BLOCKING}" = "true" ]
+		# we need to replace it with "\n"
+		ZENITY_TEXT="${TEXT//<br>/\\n}"
+		echo "ZENITY_TEXT=\"$ZENITY_TEXT\""
+		if [ "$BLOCKING" = "true" ]
 		then
-			sudo -u user zenity --error --text "${ZENITY_TEXT}"
+			sudo -u user zenity --error --no-wrap --text "$ZENITY_TEXT"
 		else
-			sudo -u user zenity --error --text "${ZENITY_TEXT}" &
+			sudo -u user zenity --error --no-wrap --text "$ZENITY_TEXT" &
 		fi
 	fi
 
 	# another variant with notify-send instead of a dialog
 	# unfortunately, this doesn't work in Debian 8 GNOME
-	# sudo -u user notify-send -i dialog-error "${ERROR_MESSAGE}"
+	# sudo -u user notify-send -i dialog-error "$ERROR_MESSAGE"
 }
 
 get_existing_parent()
 {
-	DIRECTORY="${1}"
-	while [ ! -d ${DIRECTORY} ]
+	DIRECTORY="$1"
+	while [ ! -d "$DIRECTORY" ]
 	do
-		DIRECTORY="$(dirname "${DIRECTORY}")"
+		DIRECTORY="$(dirname "$DIRECTORY")"
 	done
-	echo "${DIRECTORY}"
+	echo "$DIRECTORY"
 }
 
 reformat_backup_partition()
@@ -78,56 +78,146 @@ reformat_backup_partition()
 	then
 		# If the exchange partition is user accessible it could be used for much more than
 		# storing backups. Therefore formatting is not a valid fallback strategy in this case.
-		echo "exchange partition is user accessible, formatting canceled." | tee -a ${LOG_FILE}
+		echo "exchange partition is user accessible, formatting canceled." | tee -a $LOG_FILE
 		return
 	fi
 
 	BACKUP_PARTITION=$(grep /exchange/partition /proc/mounts | awk '{ print $1 }')
-	echo "backup partition: $BACKUP_PARTITION" | tee -a ${LOG_FILE}
-	if umount $BACKUP_PARTITION
+	echo "backup partition: $BACKUP_PARTITION" | tee -a $LOG_FILE
+	if umount "$BACKUP_PARTITION"
 	then
-		echo "unmounted backup partition before formatting" | tee -a ${LOG_FILE}
+		echo "unmounted backup partition before formatting" | tee -a $LOG_FILE
 	else
-		echo "ERROR: could not umount backup partition!" | tee -a ${LOG_FILE}
+		echo "ERROR: could not umount backup partition!" | tee -a $LOG_FILE
 	fi
-	LABEL="$(lsblk -no LABEL $BACKUP_PARTITION)"
-	echo "label: $LABEL" | tee -a ${LOG_FILE}
-	FSTYPE="$(lsblk -no FSTYPE $BACKUP_PARTITION)"
-	echo "fstype: $FSTYPE" | tee -a ${LOG_FILE}
+	LABEL="$(lsblk -no LABEL "$BACKUP_PARTITION")"
+	echo "label: $LABEL" | tee -a $LOG_FILE
+	FSTYPE="$(lsblk -no FSTYPE "$BACKUP_PARTITION")"
+	echo "fstype: $FSTYPE" | tee -a $LOG_FILE
 	case $FSTYPE in
 		ntfs)
-			mkfs.ntfs -f -L "$LABEL" $BACKUP_PARTITION
+			mkfs.ntfs -f -L "$LABEL" "$BACKUP_PARTITION"
 			;;
 		vfat)
-			mkfs.vfat -n "$LABEL" $BACKUP_PARTITION
+			mkfs.vfat -n "$LABEL" "$BACKUP_PARTITION"
 			;;
 		*)
-			echo "unsupported file format!" | tee -a ${LOG_FILE}
+			echo "unsupported file format!" | tee -a $LOG_FILE
 			;;
 	esac
-	mount $BACKUP_PARTITION /exchange/partition
+	mount "$BACKUP_PARTITION" /exchange/partition
+}
+
+backup_and_cleanup()
+{
+	if rdiff-backup -v5 "$1" "$2" >> $LOG_FILE 2>&1
+	then
+		delete_old_backups "$2"
+	else
+		return 1
+	fi
+}
+
+fallback_new_folder()
+{
+	# Sometimes (probably when an NTP time sync that jumps backwards in
+	# time happens during an rdiff-backup run) rdiff-backup just stumbles
+	# over its own feet and leaves a broken destination folder behind.
+	# Because interactive repairing can take too long and is too difficult
+	# for our users we have to use different fallback strategies.
+
+	# Our first fallback strategy is to rename the old backup folder
+	# and retry with a fresh one.
+	mv "$DESTINATION" "${DESTINATION}.old-$(date +%Y-%m-%d-%H-%M)"
+
+	echo "retrying after renaming broken destination folder" | tee -a $LOG_FILE
+	if ! backup_and_cleanup "$1" "$2"
+	then
+		# It didn't work with a new folder, so maybe we run out of disk space?
+		FREE_SPACE="$(df | grep ^"$DEVICE" | awk '{ print $4}')"
+		if [ "$FREE_SPACE" = "0" ]
+		then
+			echo "there is no free diskspace left" | tee -a $LOG_FILE
+			fallback_remove_old_backup_directories "$1" "$2"
+		else
+			show_error "$ERROR_MESSAGE"
+		fi
+	fi
+}
+
+fallback_remove_old_backup_directories()
+{
+	# We ran out of storage space on the backup destination device.
+	# Therefore, our second fallback strategy is to remove the old backup
+	# directories and try again.
+	echo "asking user for permission to remove old backup directories" | tee -a $LOG_FILE
+	if sudo -u user zenity --question --no-wrap --text "$(gettext "The backup destination device is full.\n<b>Should existing backup directories be removed to free up storage space?</b>")" --ok-label "$(gettext "Remove backup directories")"
+	then
+		echo "removing old backup destination folders" | tee -a $LOG_FILE
+		# also remove the destination folder
+		# because it contains a failed backup run
+		rm -rf "${DESTINATION}"
+		rm -rf "${DESTINATION}.old-"*
+
+		if ! backup_and_cleanup "$1" "$2"
+		then
+			fallback_reformat "$1" "$2"
+		fi
+	else
+		show_error "$ERROR_MESSAGE"
+	fi
+}
+
+fallback_reformat()
+{
+	# When a broken filesystem is mounted, the free space is sometimes also
+	# shown as 0%. Therefore, our last fallback strategy is to reformat the
+	# backup partition if this is the case and try again.
+	FREE_SPACE="$(df | grep ^"$DEVICE" | awk '{ print $4}')"
+	if [ "$FREE_SPACE" = "0" ]
+	then
+		if sudo -u user zenity --question --no-wrap --text "$(gettext "The file system on the backup destination device ($DEVICE) seems to be corrupted.\n<b>Should the backup destination device be reformattet?</b>\n<span foreground=\"red\">(This will delete previous backups from the destination device.)</span>")" --ok-label "$(gettext "Reformat device")"
+		then
+			reformat_backup_partition
+			if ! backup_and_cleanup "$1" "$2"
+			then
+				show_error "$ERROR_MESSAGE"
+			fi
+		else
+			show_error "$ERROR_MESSAGE"
+			return 1
+		fi
+	else
+		show_error "$ERROR_MESSAGE"
+	fi
 }
 
 do_rdiff()
 {
-	DESTINATION="${2}"
-	echo "planned destination directory: ${DESTINATION}" | tee -a ${LOG_FILE}
+	DESTINATION="$2"
+	ERROR_MESSAGE="$(eval_gettext "Backup to<br><tt>\${DESTINATION}</tt><br>failed!")"
+	echo "planned destination directory: $DESTINATION" | tee -a $LOG_FILE
 
 	# Sometimes the destination directory doesn't exist yet.
 	# In this case the call to df below would fail.
 	# Therefore we have to search an existing (parent) directory for df.
-	EXISTING_PARENT=$(get_existing_parent "${DESTINATION}")
-	echo "existing destination parent directory: ${EXISTING_PARENT}" | tee -a ${LOG_FILE}
+	EXISTING_PARENT=$(get_existing_parent "$DESTINATION")
+	echo "existing destination parent directory: $EXISTING_PARENT" | tee -a $LOG_FILE
 	# check if we need to run a file system check
-	DEVICE="$(df "${EXISTING_PARENT}" | grep /dev/ | awk '{ print $1}')"
-	if [ -n "${DEVICE}" ]
+	# or reformat the backup destination device
+	# (indicated by backup destination device being mounted read-only)
+	DEVICE="$(df "$EXISTING_PARENT" | grep /dev/ | awk '{ print $1}')"
+	if [ -n "$DEVICE" ]
 	then
-		echo "backup destination device: ${DEVICE}" | tee -a ${LOG_FILE}
-		if mount | grep ^"${DEVICE}" | grep "(ro," > /dev/null
+		echo "backup destination device: $DEVICE" | tee -a $LOG_FILE
+		if mount | grep ^"$DEVICE" | grep "(ro," > /dev/null
 		then
-			# The file system seems to be corrupted. Unfortunately, vfat is so fragile that this happens quite often
-			# when students just unplug the USB stick before shutdown completes.
-			# Interactive file system repairs (commented out below) turned out to be too irritating and complicated.
+			# The file system seems to be corrupted. Unfortunately,
+			# vfat is so fragile that this happens quite often when
+			# students just unplug the USB stick before shutdown
+			# completes.
+			# Interactive file system repairs (commented out below)
+			# turned out to be too irritating and complicated.
 			# Therefore we better reformat the exchange partition...
 			#
 			# ------ old version with interactive file system repair ------
@@ -137,68 +227,27 @@ do_rdiff()
 			# mount -o remount,rw "${DEVICE}"
 			#
 			# ------ new version with reformatting ------
-			reformat_backup_partition
+			if sudo -u user zenity --question --no-wrap --text "$(gettext "The file system on the backup destination device ($DEVICE) seems to be corrupted.\n<b>Should the backup destination device be reformattet?</b>\n<span foreground=\"red\">(This will delete previous backups from the destination device.)</span>")" --ok-label "$(gettext "Reformat device")"
+			then
+				reformat_backup_partition
+			else
+				show_error "$ERROR_MESSAGE"
+				return 1
+			fi
 		fi
 	fi
 
 	# make sure that the backup destination directory exists
 	# (rdiff-backup can auto-create the leaf destination directory but not
 	# all parent directories)
-	if [ ! -d "${DESTINATION}" ]
+	if [ ! -d "$DESTINATION" ]
 	then
-		mkdir -p "${DESTINATION}"
+		mkdir -p "$DESTINATION"
 	fi
 
-	if rdiff-backup -v5 "${1}" "${DESTINATION}" >> ${LOG_FILE} 2>&1
+	if ! backup_and_cleanup "$1" "$2"
 	then
-		delete_old_backups "${DESTINATION}"
-	else
-		# Sometimes rdiff-backup just stumbles over its own feet and
-		# leaves a broken destination folder behind. Because
-		# interactive repairing can take too long and is too difficult
-		# for our users we have to use different fallback strategies.
-		# Our first fallback strategy is to rename the old backup
-		# folder and retry with a fresh one.
-		echo "retrying after renaming broken destination folder" | tee -a ${LOG_FILE}
-		rm -rf "${DESTINATION}.old"
-		mv "${DESTINATION}" "${DESTINATION}.old"
-		if rdiff-backup -v5 "${1}" "${DESTINATION}" >> ${LOG_FILE} 2>&1
-		then
-			delete_old_backups "${DESTINATION}"
-		else
-			ERROR_MESSAGE="$(eval_gettext "Backup to<br><tt>\${DESTINATION}</tt><br>failed!")"
-			# It didn't work with a new folder, so maybe we run out of disk space?
-			FREE_SPACE="$(df | grep ^${DEVICE} | awk '{ print $4}')"
-			if [ "${FREE_SPACE}" = "0" ]
-			then
-				echo "there is no free diskspace left" | tee -a ${LOG_FILE}
-				echo "retrying after removing all destination folders" | tee -a ${LOG_FILE}
-				rm -rf "${DESTINATION}"
-				rm -rf "${DESTINATION}.old"
-				if rdiff-backup -v5 "${1}" "${DESTINATION}" >> ${LOG_FILE} 2>&1
-				then
-					delete_old_backups "${DESTINATION}"
-				else
-					FREE_SPACE="$(df | grep ^${DEVICE} | awk '{ print $4}')"
-					if [ "${FREE_SPACE}" = "0" ]
-					then
-						# when a broken filesystem is mounted the free space is sometimes also shown as 0%
-						# therefore we also retry with reformatting here
-						reformat_backup_partition
-						if rdiff-backup -v5 "${1}" "${DESTINATION}" >> ${LOG_FILE} 2>&1
-						then
-							delete_old_backups "${DESTINATION}"
-						else
-							show_error "${ERROR_MESSAGE}"
-						fi
-					else
-						show_error "${ERROR_MESSAGE}"
-					fi
-				fi
-			else
-				show_error "${ERROR_MESSAGE}"
-			fi
-		fi
+		fallback_new_folder "$1" "$2"
 	fi
 }
 
@@ -214,19 +263,19 @@ delete_old_backups()
 	# There are at least 5 files per backup timestamp, so limiting the number
 	# of backups to 500 seems to be a good default.
 	MAX_COUNTER=500
-	echo "trying to keep only ${MAX_COUNTER} backups..." | tee -a ${LOG_FILE}
+	echo "trying to keep only $MAX_COUNTER backups..." | tee -a $LOG_FILE
 	COUNTER=$(rdiff-backup -l --parsable-output "$1" | wc -l)
-	echo "There are ${COUNTER} backups" | tee -a ${LOG_FILE}
-	OVERHEAD=$((${COUNTER}-${MAX_COUNTER}))
-	echo "overhead: ${OVERHEAD}" | tee -a ${LOG_FILE}
-	if [ ${OVERHEAD} -gt 0 ]
+	echo "There are $COUNTER backups" | tee -a $LOG_FILE
+	OVERHEAD=$((COUNTER-MAX_COUNTER))
+	echo "overhead: $OVERHEAD" | tee -a $LOG_FILE
+	if [ $OVERHEAD -gt 0 ]
 	then
-		echo "we should delete old backups" | tee -a ${LOG_FILE}
-		TIMESTAMP=$(rdiff-backup -l --parsable-output $1 | sed -n $((${OVERHEAD}+1))p | awk '{ print $1 }')
-		echo "last timestamp to keep: ${TIMESTAMP}" | tee -a ${LOG_FILE}
-		rdiff-backup --force --remove-older-than ${TIMESTAMP} "$1"
+		echo "we should delete old backups" | tee -a $LOG_FILE
+		TIMESTAMP=$(rdiff-backup -l --parsable-output "$1" | sed -n $((OVERHEAD+1))p | awk '{ print $1 }')
+		echo "last timestamp to keep: $TIMESTAMP" | tee -a $LOG_FILE
+		rdiff-backup --force --remove-older-than "$TIMESTAMP" "$1"
 	else
-		echo "we don't need to delete old backups" | tee -a ${LOG_FILE}
+		echo "we don't need to delete old backups" | tee -a $LOG_FILE
 	fi
 }
 
@@ -242,10 +291,10 @@ do_backup()
 	if [ "${CONFIG[BackupScreenshot]}" = "true" ]
 	then
 		# make sure that the screenshots directory exists
-		if [ ! -d "${SCREENSHOT_DIRECTORY}" ]
+		if [ ! -d "$SCREENSHOT_DIRECTORY" ]
 		then
-			mkdir -p "${SCREENSHOT_DIRECTORY}"
-			chmod 700 "${SCREENSHOT_DIRECTORY}"
+			mkdir -p "$SCREENSHOT_DIRECTORY"
+			chmod 700 "$SCREENSHOT_DIRECTORY"
 		fi
 		sudo -u user import -silent -window root jpg:- | convert - \
 			-filter Triangle \
@@ -273,31 +322,31 @@ do_backup()
 	if [ "${CONFIG[BackupPartitionEnabled]}" = "true" ]
 	then
 		BACKUP_DEVICE="$(blkid -l -o device -t LABEL="${CONFIG[BackupPartition]}")"
-		if [ ${BACKUP_DEVICE} ]
+		if [ "$BACKUP_DEVICE" ]
 		then
-			MOUNT_POINT="$(grep ${BACKUP_DEVICE} /proc/mounts | awk '{ print $2 }')"
-			echo "mount point of ${BACKUP_DEVICE}: \"${MOUNT_POINT}\"" | tee -a ${LOG_FILE}
-			if [ -z "${MOUNT_POINT}" ]
+			MOUNT_POINT="$(grep "$BACKUP_DEVICE" /proc/mounts | awk '{ print $2 }')"
+			echo "mount point of ${BACKUP_DEVICE}: \"${MOUNT_POINT}\"" | tee -a $LOG_FILE
+			if [ -z "$MOUNT_POINT" ]
 			then
 				MOUNT_DIR="/backup/"
 				MOUNT_POINT="${MOUNT_DIR}/${CONFIG[BackupPartition]}"
-				mkdir -p "${MOUNT_POINT}"
-				chown root.root "${MOUNT_DIR}"
-				chmod 700  "${MOUNT_DIR}"
-				echo "calling \"mount ${BACKUP_DEVICE} ${MOUNT_POINT}\"" | tee -a ${LOG_FILE}
-				mount ${BACKUP_DEVICE} "${MOUNT_POINT}"
+				mkdir -p "$MOUNT_POINT"
+				chown root.root "$MOUNT_DIR"
+				chmod 700  "$MOUNT_DIR"
+				echo "calling \"mount $BACKUP_DEVICE $MOUNT_POINT\"" | tee -a $LOG_FILE
+				mount "$BACKUP_DEVICE" "$MOUNT_POINT"
 			fi
 			if [[ ${CONFIG[BackupDirectory]} == /exchange/partition/* ]]
 			then
-				echo "backup directory on mounted exchange partition" | tee -a ${LOG_FILE}
+				echo "backup directory on mounted exchange partition" | tee -a $LOG_FILE
 				PARTITION_BACKUP_DIR="${CONFIG[BackupDirectory]/#\/exchange\/partition\//}"
 			else
 				PARTITION_BACKUP_DIR="lernstick_backup"
 			fi
-			echo "PARTITION_BACKUP_DIR=\"$PARTITION_BACKUP_DIR\"" | tee -a ${LOG_FILE}
+			echo "PARTITION_BACKUP_DIR=\"$PARTITION_BACKUP_DIR\"" | tee -a $LOG_FILE
 			do_rdiff "${CONFIG[BackupSource]}" "${MOUNT_POINT}/$PARTITION_BACKUP_DIR"
-			echo "unmounting ${BACKUP_DEVICE} so that it can be temporarily removed" | tee -a ${LOG_FILE}
-			umount ${BACKUP_DEVICE}
+			echo "unmounting $BACKUP_DEVICE so that it can be temporarily removed" | tee -a $LOG_FILE
+			umount "$BACKUP_DEVICE"
 		else
 			BP_TMP="${CONFIG[BackupPartition]}"
 			show_error "$(eval_gettext "Backup partition<br><tt>\${BP_TMP}</tt><br>not found!")"
@@ -309,47 +358,47 @@ do_backup()
 }
 
 # add newline if logfile is not empty
-if [ -f ${LOG_FILE} ]
+if [ -f $LOG_FILE ]
 then
-	SIZE=$(wc -c < ${LOG_FILE})
-	if [ "${SIZE}" != "0" ]
+	SIZE=$(wc -c < $LOG_FILE)
+	if [ "$SIZE" != "0" ]
 	then
-		echo "" >> ${LOG_FILE}
+		echo "" >> $LOG_FILE
 	fi
 fi
 
 if [ "$1" = "once" ]
 then
-	echo "FINAL backup run at $(date -R)" | tee -a ${LOG_FILE}
+	echo "FINAL backup run at $(date -R)" | tee -a $LOG_FILE
 	do_backup
 else
-	TIMEOUT=$(expr ${CONFIG[BackupFrequency]} \* 60)
+	TIMEOUT=$(("${CONFIG[BackupFrequency]}" * 60))
 	while true; do
-		echo "backup run at $(date -R)" | tee -a ${LOG_FILE}
+		echo "backup run at $(date -R)" | tee -a $LOG_FILE
 
 		# get current time
 		BEFORE="$(date +%s)"
-		echo "system time in seconds before running backup: ${BEFORE}" | tee -a ${LOG_FILE}
+		echo "system time in seconds before running backup: $BEFORE" | tee -a $LOG_FILE
 
 		# execute command
 		do_backup
 
 		# wait until TIMEOUT is over
 		AFTER="$(date +%s)"
-		echo "system time in seconds after running backup: ${AFTER}" | tee -a ${LOG_FILE}
+		echo "system time in seconds after running backup: $AFTER" | tee -a $LOG_FILE
 		# Now that we enabled ntp updates in the exam environment, the following
 		# timeout calucation breaks when the system time changes while the backup is
 		# running. Yes, we already run into this issue in the real world during a real exam...
 		# Therefore we simply sleep for the configured timeout instead of trying to
 		# stay close to the configured backup frequency.
 		# SLEEP=$(expr ${TIMEOUT} - ${AFTER} + ${BEFORE})
-		SLEEP=${TIMEOUT}
-		if [ ${SLEEP} -gt 0 ]
+		SLEEP=$TIMEOUT
+		if [ "$SLEEP" -gt 0 ]
 		then
-			echo "sleeping for ${SLEEP} seconds..." | tee -a ${LOG_FILE}
-			sleep ${SLEEP}
+			echo "sleeping for $SLEEP seconds..." | tee -a $LOG_FILE
+			sleep "$SLEEP"
 		else
-			echo "timeout already passed!" | tee -a ${LOG_FILE}
+			echo "timeout already passed!" | tee -a $LOG_FILE
 		fi
 	done
 fi
